apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-tls
  annotations:
    cert-manager.io/issue-temporary-certificate:  "true"
spec:
  secretName: headlamp-tls
  issuerRef:
{% if "cert_manager" in components %}
{% if cert_manager_config.admin_mail is defined %}
    name: letsencrypt-prod
{% else %}
    name: gubernat-issuer
{% endif %}
{% else %}
    name: unused
{% endif %}
    kind: ClusterIssuer
  commonName: {{ headlamp_config.tls_host }}
  dnsNames:
    -  {{ headlamp_config.tls_host }}
  