apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
    nodePort: {{ contour_config.http_nodeport }}
  - port: 443
    name: https
    protocol: TCP
    targetPort: 8443
    nodePort: {{ contour_config.ssl_nodeport }}
  selector:
    app: envoy
  type: NodePort