# increase inotify for k8s (circumvent "failed to create fsnotify watcher: too many open files" error)
fs.inotify.max_user_watches = 2099999999
fs.inotify.max_user_instances = 2099999999
fs.inotify.max_queued_events = 2099999999
